[project]
name = "snake"
version = "0.1.0"
description = "Snake, The Game"
authors = [
    {name = "samspriggs94",email = "samspriggs94@outlook.com"}
]
license = {text = "None"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
