name: Build & Release EXE
# Uses windows as I can only test locally on a windows machine.

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and Release
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry install --no-root

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          $version = poetry version -s
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Get latest GitHub release version
        id: get_latest_release
        shell: bash
        run: |
          LATEST=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: version_check
        shell: bash
        run: |
          CURRENT="${{ steps.get_version.outputs.version }}"
          LATEST="${{ steps.get_latest_release.outputs.latest }}"
          if [ "$(printf "$LATEST\n$CURRENT" | sort -V | tail -n1)" = "$CURRENT" ] && [ "$CURRENT" != "$LATEST" ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Install PyInstaller
        if: steps.version_check.outputs.should_release == 'true'
        run: poetry run pip install pyinstaller

      - name: Build EXE with PyInstaller
        if: steps.version_check.outputs.should_release == 'true'
        run: |
          poetry run pyinstaller --onefile znakegame/main.py
          mkdir dist-upload
          move dist\main.exe dist-upload\znake.exe

      - name: Create GitHub Release
        if: steps.version_check.outputs.should_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          files: dist-upload/znake.exe
